// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using domain.pipeline.fourth.com.Models;

namespace domain.pipeline.fourth.com.Migrations
{
    [DbContext(typeof(FourthPipelineContext))]
    [Migration("20200310201508_latest")]
    partial class latest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("com.fourth.pipeline.pos.Model.RevenueCenterCategoryMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FourthSalesApiStoreConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FourthSalesApiStoreConfigId");

                    b.ToTable("RevenueCenterCategoryMappings");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("InitalSetupSytemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.BrandIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("IntegrationSubType")
                        .HasColumnType("int");

                    b.Property<int>("IntegrationType")
                        .HasColumnType("int");

                    b.Property<int?>("StartBatchQueryTimeUTC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("BrandIntegrations");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.FourthSalesApiStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("RevenueCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevenueCenterMappingType")
                        .HasColumnType("int");

                    b.Property<string>("SiteLocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreIntegrationId")
                        .HasColumnType("int");

                    b.Property<string>("UnitId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("FourthSalesApiStoreConfig");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.LightspeedRestoStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LsRestoCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("StoreIntegrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("LightspeedRestoStoreConfig");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.RevelStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("EstablishmentID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstablishmentResourceUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreIntegrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("RevelStoreConfigs");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.SquareStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("LocationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreIntegrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("SquareStoreConfigs");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Credentials.BaseCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BaseEndpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CredentialType")
                        .HasColumnType("int");

                    b.Property<string>("KeySecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestAccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("SupplimentalData1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplimentalData2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("StoreId");

                    b.ToTable("CredentialsPool");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Global", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Globals");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UTCOffsetInHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.StoreIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("IntegrationSubType")
                        .HasColumnType("int");

                    b.Property<int>("IntegrationType")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("StoreIntegrations");
                });

            modelBuilder.Entity("com.fourth.pipeline.pos.Model.RevenueCenterCategoryMapping", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Configs.Store.FourthSalesApiStoreConfig", null)
                        .WithMany("RevenueCenterCategoryMappings")
                        .HasForeignKey("FourthSalesApiStoreConfigId");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.BrandIntegration", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Brand", "Brand")
                        .WithMany("BrandIntegrations")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.FourthSalesApiStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("FourthSalesApiStoreConfigs")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.LightspeedRestoStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("LightspeedRestoStoreConfig")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.RevelStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("RevelStoreConfigs")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.SquareStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("SquareStoreConfigs")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Credentials.BaseCredential", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Brand", "Brand")
                        .WithMany("BrandCredentials")
                        .HasForeignKey("BrandId");

                    b.HasOne("data.pipeline.fourth.com.Models.Store", "Store")
                        .WithMany("StoreCredentials")
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Store", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Brand", "Brand")
                        .WithMany("Stores")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.StoreIntegration", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Store", "Store")
                        .WithMany("StoreIntegrations")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
