// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using domain.pipeline.fourth.com.Models;

namespace domain.pipeline.fourth.com.Migrations
{
    [DbContext(typeof(FourthPipelineContext))]
    [Migration("20200201232412_updateDAtts")]
    partial class updateDAtts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("com.fourth.pipeline.pos.Model.RevenueCenterCategoryMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryId");

                    b.Property<string>("CategoryName");

                    b.Property<int?>("FourthSalesApiStoreConfigId");

                    b.HasKey("Id");

                    b.HasIndex("FourthSalesApiStoreConfigId");

                    b.ToTable("RevenueCenterCategoryMappings");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactName");

                    b.Property<int>("InitalSetupSytemType");

                    b.Property<string>("Name");

                    b.Property<int>("Region");

                    b.Property<DateTime>("WhenCreatedUTC");

                    b.Property<DateTime>("WhenUpdatedUTC");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.BrandIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<int>("BrandId");

                    b.Property<int>("IntegrationSubType");

                    b.Property<int>("IntegrationType");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("BrandIntegrations");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.FourthSalesApiStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("RevenueCenter");

                    b.Property<int>("RevenueCenterMappingType");

                    b.Property<string>("SiteLocationCode");

                    b.Property<int>("StoreIntegrationId");

                    b.Property<string>("UnitId");

                    b.Property<DateTime>("WhenCreatedUTC");

                    b.Property<DateTime>("WhenUpdatedUTC");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("FourthSalesApiStoreConfig");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.LightspeedRestoStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CompanyId");

                    b.Property<int>("StoreIntegrationId");

                    b.Property<DateTime>("WhenCreatedUTC");

                    b.Property<DateTime>("WhenUpdatedUTC");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("LightspeedRestoStoreConfig");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.RevelStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("EstablishmentID");

                    b.Property<string>("EstablishmentResourceUri");

                    b.Property<int>("StoreIntegrationId");

                    b.Property<DateTime>("WhenCreatedUTC");

                    b.Property<DateTime>("WhenUpdatedUTC");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("RevelStoreConfigs");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.SquareStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("LocationId");

                    b.Property<int>("StoreIntegrationId");

                    b.Property<DateTime>("WhenCreatedUTC");

                    b.Property<DateTime>("WhenUpdatedUTC");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("SquareStoreConfigs");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Credentials.BaseCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("BaseEndpoint");

                    b.Property<int?>("BrandId");

                    b.Property<string>("ClientId");

                    b.Property<string>("ClientSecret");

                    b.Property<int>("CredentialType");

                    b.Property<string>("KeySecret");

                    b.Property<string>("LatestAccessToken");

                    b.Property<string>("Password");

                    b.Property<string>("RefreshToken");

                    b.Property<int?>("StoreId");

                    b.Property<string>("SupplimentalData1");

                    b.Property<string>("SupplimentalData2");

                    b.Property<string>("Username");

                    b.Property<DateTime>("WhenCreatedUTC");

                    b.Property<DateTime>("WhenUpdatedUTC");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("StoreId");

                    b.ToTable("CredentialsPool");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Global", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Globals");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<int>("BrandId");

                    b.Property<string>("Name");

                    b.Property<string>("Timezone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.StoreIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("EndBatchTimeUTC");

                    b.Property<DateTime>("FireTimeUTC");

                    b.Property<int>("IntegrationSubType");

                    b.Property<int>("IntegrationType");

                    b.Property<DateTime>("StartBatchTimeUTC");

                    b.Property<int>("StoreId");

                    b.Property<DateTime>("WhenCreatedUTC");

                    b.Property<DateTime>("WhenUpdatedUTC");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("StoreIntegrations");
                });

            modelBuilder.Entity("com.fourth.pipeline.pos.Model.RevenueCenterCategoryMapping", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Configs.Store.FourthSalesApiStoreConfig")
                        .WithMany("RevenueCenterCategoryMappings")
                        .HasForeignKey("FourthSalesApiStoreConfigId");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.BrandIntegration", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Brand", "Brand")
                        .WithMany("BrandIntegrations")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.FourthSalesApiStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("FourthSalesApiStoreConfigs")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.LightspeedRestoStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("LightspeedRestoStoreConfig")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.RevelStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("RevelStoreConfigs")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.SquareStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("SquareStoreConfigs")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Credentials.BaseCredential", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Brand", "Brand")
                        .WithMany("BrandCredentials")
                        .HasForeignKey("BrandId");

                    b.HasOne("data.pipeline.fourth.com.Models.Store", "Store")
                        .WithMany("StoreCredentials")
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Store", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Brand", "Brand")
                        .WithMany("Stores")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.StoreIntegration", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Store", "Store")
                        .WithMany("StoreIntegrations")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
