// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using domain.pipeline.fourth.com.Models;

#nullable disable

namespace domain.pipeline.fourth.com.Migrations
{
    [DbContext(typeof(FourthPipelineContext))]
    [Migration("20260704230556_pipelineRunRecords")]
    partial class pipelineRunRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("com.fourth.pipeline.pos.Model.RevenueCenterCategoryMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FourthSalesApiStoreConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FourthSalesApiStoreConfigId");

                    b.ToTable("RevenueCenterCategoryMappings");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("InitalSetupSytemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.BrandIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("IntegrationSubType")
                        .HasColumnType("int");

                    b.Property<int>("IntegrationType")
                        .HasColumnType("int");

                    b.Property<int?>("StartBatchQueryTimeUTC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("BrandIntegrations");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.FourthSalesApiStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("RevenueCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevenueCenterMappingType")
                        .HasColumnType("int");

                    b.Property<string>("SiteLocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreIntegrationId")
                        .HasColumnType("int");

                    b.Property<string>("UnitId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("FourthSalesApiStoreConfig");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.LightspeedRestoStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LsRestoCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("StoreIntegrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("LightspeedRestoStoreConfig");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.RevelStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("EstablishmentID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstablishmentResourceUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreIntegrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("RevelStoreConfigs");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.SquareStoreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("LocationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreIntegrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId");

                    b.ToTable("SquareStoreConfigs");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Credentials.BaseCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BaseEndpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CredentialType")
                        .HasColumnType("int");

                    b.Property<string>("KeySecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestAccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("SupplimentalData1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplimentalData2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("StoreId");

                    b.ToTable("CredentialsPool");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Global", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Globals");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Mappings.SquareEmployeeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("FourthEmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SquareDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SquareTeamMemberId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("StoreIntegrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId", "SquareTeamMemberId")
                        .IsUnique()
                        .HasDatabaseName("IX_SquareEmployeeMappings_StoreIntegrationId_SquareTeamMemberId_Active")
                        .HasFilter("[Active] = 1");

                    b.ToTable("SquareEmployeeMappings");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.PipelineRunRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("BrandName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DataType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FourthLocationCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FourthResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FourthStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("FourthUnitId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OutputFileName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("OutputFullPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadFormat")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SquareLocationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<int?>("StoreIntegrationId")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TargetSystem")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreIntegrationId", "DataType", "TransactionDate");

                    b.ToTable("PipelineRunRecords");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UTCOffsetInHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.StoreIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("IntegrationSubType")
                        .HasColumnType("int");

                    b.Property<int>("IntegrationType")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("StoreIntegrations");
                });

            modelBuilder.Entity("com.fourth.pipeline.pos.Model.RevenueCenterCategoryMapping", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Configs.Store.FourthSalesApiStoreConfig", null)
                        .WithMany("RevenueCenterCategoryMappings")
                        .HasForeignKey("FourthSalesApiStoreConfigId");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.BrandIntegration", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Brand", "Brand")
                        .WithMany("BrandIntegrations")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.FourthSalesApiStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("FourthSalesApiStoreConfigs")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreIntegration");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.LightspeedRestoStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("LightspeedRestoStoreConfig")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreIntegration");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.RevelStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("RevelStoreConfigs")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreIntegration");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.SquareStoreConfig", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("SquareStoreConfigs")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreIntegration");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Credentials.BaseCredential", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Brand", "Brand")
                        .WithMany("BrandCredentials")
                        .HasForeignKey("BrandId");

                    b.HasOne("data.pipeline.fourth.com.Models.Store", "Store")
                        .WithMany("StoreCredentials")
                        .HasForeignKey("StoreId");

                    b.Navigation("Brand");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Mappings.SquareEmployeeMapping", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.StoreIntegration", "StoreIntegration")
                        .WithMany("SquareEmployeeMappings")
                        .HasForeignKey("StoreIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreIntegration");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Store", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Brand", "Brand")
                        .WithMany("Stores")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.StoreIntegration", b =>
                {
                    b.HasOne("data.pipeline.fourth.com.Models.Store", "Store")
                        .WithMany("StoreIntegrations")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Brand", b =>
                {
                    b.Navigation("BrandCredentials");

                    b.Navigation("BrandIntegrations");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Configs.Store.FourthSalesApiStoreConfig", b =>
                {
                    b.Navigation("RevenueCenterCategoryMappings");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.Store", b =>
                {
                    b.Navigation("StoreCredentials");

                    b.Navigation("StoreIntegrations");
                });

            modelBuilder.Entity("data.pipeline.fourth.com.Models.StoreIntegration", b =>
                {
                    b.Navigation("FourthSalesApiStoreConfigs");

                    b.Navigation("LightspeedRestoStoreConfig");

                    b.Navigation("RevelStoreConfigs");

                    b.Navigation("SquareEmployeeMappings");

                    b.Navigation("SquareStoreConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
