//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Geckoboard._808nd.com
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;


    /// <summary>
    /// This is a top level class - it's never used, but specific decendents hold specific items that go in 
    /// the 'data' of an object
    /// </summary>
    public class Item
    {

        public Item()
        {

        }

        public Item(GeckoboardChartAndItemType type)
        {
            this.Type = type;
        }

        //properties
        protected GeckoboardChartAndItemType Type { get; set; }



        public bool ShouldSerializeType()
        {
            // don't serialize the Manager property if an employee is their own manager
            return (false);
        }

    }
}

