//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[GeneratedCode("xsd", "4.0.30319.33440")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
[XmlRoot(Namespace="", IsNullable=false)]
public partial class FourthHeader {
    
    private List<FourthHeaderOrganisationHeader> organisationHeaderField;
    
    /// <remarks/>
    [XmlElement("OrganisationHeader")]
	public List<FourthHeaderOrganisationHeader> OrganisationHeader
	{
		get
		{
			return this.organisationHeaderField;
		}
		set
		{
			this.organisationHeaderField = value;
		}
	}
}

/// <remarks/>
[GeneratedCode("xsd", "4.0.30319.33440")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
public partial class FourthHeaderOrganisationHeader {
    
    private string organisationIDField;
    
    private string userNameField;
    
    private string passwordField;
    
    private List<FourthHeaderOrganisationHeaderSalesHeader> salesHeaderField;
    
    /// <remarks/>
    public string OrganisationID {
        get {
            return this.organisationIDField;
        }
        set {
            this.organisationIDField = value;
        }
    }
    
    /// <remarks/>
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("SalesHeader")]
	public List<FourthHeaderOrganisationHeaderSalesHeader> SalesHeader
	{
		get
		{
			return this.salesHeaderField;
		}
		set
		{
			this.salesHeaderField = value;
		}
	}
}

/// <remarks/>
[GeneratedCode("xsd", "4.0.30319.33440")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
public partial class FourthHeaderOrganisationHeaderSalesHeader {
    
    private DateTime salesDateField;
    
    private string locationField;
    
    private string revenueCentreField;
    
    private actionide actionIfDataExistsField;
    
    private List<FourthHeaderOrganisationHeaderSalesHeaderSalesTransaction> salesTransactionField;
    
    public FourthHeaderOrganisationHeaderSalesHeader() {
        this.locationField = "1";
        this.revenueCentreField = "1";
        this.actionIfDataExistsField = actionide.Item2;
    }
    
    /// <remarks/>
    [XmlElement(DataType="date")]
    public DateTime SalesDate {
        get {
            return this.salesDateField;
        }
        set {
            this.salesDateField = value;
        }
    }
    
    /// <remarks/>
    public string Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    public string RevenueCentre {
        get {
            return this.revenueCentreField;
        }
        set {
            this.revenueCentreField = value;
        }
    }
    
    /// <remarks/>
    [DefaultValue(actionide.Item2)]
    public actionide ActionIfDataExists {
        get {
            return this.actionIfDataExistsField;
        }
        set {
            this.actionIfDataExistsField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("SalesTransaction")]
	public List<FourthHeaderOrganisationHeaderSalesHeaderSalesTransaction> SalesTransaction
	{
		get
		{
			return this.salesTransactionField;
		}
		set
		{
			this.salesTransactionField = value;
		}
	}
}

/// <remarks/>
[GeneratedCode("xsd", "4.0.30319.33440")]
[Serializable()]
public enum actionide {
    
    /// <remarks/>
    [XmlEnum("1")]
    Item1,
    
    /// <remarks/>
    [XmlEnum("2")]
    Item2,
    
    /// <remarks/>
    [XmlEnum("3")]
    Item3,
}

/// <remarks/>
[GeneratedCode("xsd", "4.0.30319.33440")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
public partial class FourthHeaderOrganisationHeaderSalesHeaderSalesTransaction {
    
    private string pLUField;
    
    private string descriptionField;
    
    private decimal quantityField;
    
    private decimal vATField;
    
    private decimal totalGrossSalesField;
    
    private decimal netSalesPriceField;
    
    private bool netSalesPriceFieldSpecified;
    
    private decimal grossSalesPriceField;
    
    private bool grossSalesPriceFieldSpecified;
    
    private decimal totalNetSalesField;
    
    private bool totalNetSalesFieldSpecified;
    
    private string categoryCodeField;
    
    private string saleTypeField;
    
    public FourthHeaderOrganisationHeaderSalesHeaderSalesTransaction() {
        this.saleTypeField = "1";
    }
    
    /// <remarks/>
    [XmlElement(DataType="nonNegativeInteger")]
    public string PLU {
        get {
            return this.pLUField;
        }
        set {
            this.pLUField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public decimal Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public decimal VAT {
        get {
            return this.vATField;
        }
        set {
            this.vATField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalGrossSales {
        get {
            return this.totalGrossSalesField;
        }
        set {
            this.totalGrossSalesField = value;
        }
    }
    
    /// <remarks/>
    public decimal NetSalesPrice {
        get {
            return this.netSalesPriceField;
        }
        set {
            this.netSalesPriceField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool NetSalesPriceSpecified {
        get {
            return this.netSalesPriceFieldSpecified;
        }
        set {
            this.netSalesPriceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal GrossSalesPrice {
        get {
            return this.grossSalesPriceField;
        }
        set {
            this.grossSalesPriceField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool GrossSalesPriceSpecified {
        get {
            return this.grossSalesPriceFieldSpecified;
        }
        set {
            this.grossSalesPriceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalNetSales {
        get {
            return this.totalNetSalesField;
        }
        set {
            this.totalNetSalesField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool TotalNetSalesSpecified {
        get {
            return this.totalNetSalesFieldSpecified;
        }
        set {
            this.totalNetSalesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string CategoryCode {
        get {
            return this.categoryCodeField;
        }
        set {
            this.categoryCodeField = value;
        }
    }
    
    /// <remarks/>
    [DefaultValue("1")]
    public string SaleType {
        get {
            return this.saleTypeField;
        }
        set {
            this.saleTypeField = value;
        }
    }
}
