//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GeckoboardLibrary.Classes;

namespace Geckoboard._808nd.com
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class NumberSecondaryStat : GeckoboardObject
	{
       public Data data { get; set; }

      public NumberSecondaryStat() : base()
	    {
	        this.data = new Data();
	    }

      public NumberSecondaryStat(int id, string api_key, string pushURL, string chartName, GeckoboardChartAndItemType type)
          : base(api_key, pushURL, chartName, type, id)
        {
             //anything else?
             this.data = new Data();
        }




      

	}
}

