//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Geckoboard._808nd.com;
using GeckoboardLibrary.Classes;
using GeckoboardLibrary.Classes.WidgetItems;

namespace Geckoboard._808nd.com
{

    public class Text : GeckoboardObject
    {
        public TextData data { get; set; }

        public Text()
            : base()
        {
            this.data = new TextData();

        }

        public Text(int id, string api_key, string pushURL, string chartName, GeckoboardChartAndItemType type)
            : base(api_key, pushURL, chartName, type, id)
        {
            //anything else?
            this.data = new TextData();
            this.data.item = new List<Item_Text>();
        }


    }


    public class TextData
    {
        public List<Item_Text> item { get; set; }

    }

}

