<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Square" Version="43.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\shared.pipeline.fouth.com\shared.pipeline.fouth.com.csproj" />
  </ItemGroup>

</Project>
