//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GeckoboardLibrary.Classes.WidgetItems;

namespace Geckoboard._808nd.com
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IGeckoboardObjectCreatorFactory 
	{
		GeckoboardOrganisation GeckoboardOrganisation { get;set; }

//		void CreateNewGeckoboardObject();

//		void CreateFunnel();

        Line CreateLine(int id, string chartName, string pushURL, List<decimal> items, LineSettings settings);

		List CreateList(int id, string chartName, string pushURL, List<Item_List> items);

	//	void CreateMonitoring();

        Bullet CreateBullet(int id, string chartName, string pushURL, string orientation, BulletItem item);

	    NumberSecondaryStat CreateNumberSecondaryStat(int id, string chartName, string pushURL, string firstStatName,
	        int firstStatvalue, string comparisonName, int comparisonValue);

	//	void CreatePie();
	    Text CreateText(int id, string chartName, string pushURL, List<Item_Text> theItems);


	    //to create data

	    //to create Items
	    //    void CreateItem();


	}
}

