//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Geckoboard._808nd.com
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IGeckoboardObject 
	{
		
        GeckoboardChartAndItemType type { get;set; }
		string pushURL { get;set; }
		string chartName { get;set; }
		string api_key { get;set; }
		Data data { get;set; }

	}
}

