//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using GeckoboardLibrary.Classes;

namespace Geckoboard._808nd.com
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface    IGeckoboardPushService 
	{
/*
		void ToNumberSecondaryStat();

		void ToText();

		void ToPie();

		void CheckValidInput();

		void ToFunnel();

		void ToMonitoring();

		void ToLine();
*/
        string WidgetToJSON(GeckoboardObject aGeckoboardObject);
        Task<bool> Push(GeckoboardObject aGeckoboardObject);

/*		void ToList();*/

	}
}

