//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Geckoboard._808nd.com
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Geckoboard._808nd;

	public class Data
	{
        public List<Item> item {get;set;}

	    public Data()
	    {
	     this.item = 
	        new List<Item>();
	    }
	}
}

