//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Geckoboard._808nd.com
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GeckoboardOrganisation
	{

	    public GeckoboardOrganisation(string api_key, string OrgName)
	    {
	        this.api_key = api_key;
	        this.OrganisationName = OrgName;

	    }

		public virtual string OrganisationName
		{
			get;
			set;
		}

		public virtual string api_key
		{
			get;
			set;
		}

	}
}

