//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Geckoboard._808nd.com
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum GeckoboardChartAndItemType
	{
		Funnel,
		Line,
		Monitoring,
		NumberSecondaryStat,
		Pie,
		Text,
		List,
        Bullet,
        LineV2,
        Leaderboard

	}
}
