// <auto-generated />
namespace Revel._808nd.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class initCreATE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initCreATE));
        
        string IMigrationMetadata.Id
        {
            get { return "202512191545217_initCreATE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
