<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>aspnet-web.pipeline.fourth.com-B41DCE88-E682-460B-90C4-0C62E5EDEB0D</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <ApplicationIcon />
    <OutputType>WinExe</OutputType>
    <StartupObject />
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.0.0" />
  </ItemGroup>


  <ItemGroup>

    <ProjectReference Include="..\com.fourth.pipeline.credentials\com.fourth.pipeline.credentials.csproj" />
    <ProjectReference Include="..\data.pipeline.fourth.com\data.pipeline.fourth.com.csproj" />
    <ProjectReference Include="..\domain.pipeline.fourth.com\domain.pipeline.fourth.com.csproj" />
    <ProjectReference Include="..\com.fourth.pipeline.pos\com.fourth.pipeline.pos.csproj" />
    <ProjectReference Include="..\shared.pipeline.fouth.com\shared.pipeline.fouth.com.csproj" />
  </ItemGroup>

</Project>
