server {
    listen 80;
    server_name squaresap.store;
    location ^~ /.well-known/acme-challenge/ {
        root C:/nginx/acme-root;
        default_type text/plain;
        try_files $uri =404;
    }
    location / { return 301 https://squaresap.store$request_uri; }
}
