<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>dotnet-squareservice.pipeline.fourth.com-9FEB8F29-C013-4F93-8163-DEC5698535FC</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
    <PackageReference Include="Quartz" Version="3.13.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\data.pipeline.fourth.com\data.pipeline.fourth.com.csproj" />
    <ProjectReference Include="..\domain.pipeline.fourth.com\domain.pipeline.fourth.com.csproj" />
    <ProjectReference Include="..\square.pipeline.fourth.com\square.pipeline.fourth.com.csproj" />
  </ItemGroup>
</Project>
