<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Email" Version="4.0.0" />
    <PackageReference Include="Shouldly" Version="4.2.1" />
    <PackageReference Include="Square" Version="43.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\data.pipeline.fourth.com\data.pipeline.fourth.com.csproj" />
    <ProjectReference Include="..\domain.pipeline.fourth.com\domain.pipeline.fourth.com.csproj" />
    <ProjectReference Include="..\com.fourth.pipeline.pos\com.fourth.pipeline.pos.csproj" />
    <ProjectReference Include="..\shared.pipeline.fouth.com\shared.pipeline.fouth.com.csproj" />
    <ProjectReference Include="..\square.pipeline.fourth.com\square.pipeline.fourth.com.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="NewFolder\" />
  </ItemGroup>

</Project>
